### PR TITLE
compute erlang_package_url from configurable host + heroku stack

### PR DESCRIPTION
**Pull request by anulman**
This PR is intended to make the buildpack more configurable by end users who may run their own Erlang build hosts 😄

### CODE REVIEW

**Comment by anulman** [comment]
Added a commit to clear the cache less aggressively, since virtually anyone upgrading to heroku-18 will deal with this issue as well (ie fixes #138).

If you would like these as separate PRs, please let me know.

**Comment by HashNuke** [comment]
@anulman Thank you for the PR.
We can merge the erlang package host changes.

As for the cache issue, I'll need some help confirming with the changes with anyone else actively using the buildpack.

**Comment by anulman** [comment]
Tagging @pwightman @mischov—this PR "works on my machine"; can you independently validate?

**Comment by anulman** [comment]
@axelson given your comment on the meeseeks issue, thought I should tag you too. Please to independently validate? 😄

**Comment by axelson** [comment]
@anulman just tested it out and everything is working smoothly 👍

**Comment by anulman** [comment]
Thanks @axelson!

@HashNuke per Jason's comment on the issue thread, he specifically means the caching change is working as expected: https://github.com/mischov/meeseeks/issues/49#issuecomment-484695089

**Comment by axelson** [comment]
@HashNuke is there anything else this PR needs before it's ready to merge?

**Comment by HashNuke** [comment]
@axelson @anulman Thank you very much for contributing a fix and testing it out ~!
I've merged the PR.

**Comment by arfl** [comment]
There is an issue related to this code change #150

**Comment by HashNuke** [comment]
Will be reverting this PR since this introduces an issue.

**Comment by HashNuke** [comment]
* Reverted the PR https://github.com/HashNuke/heroku-buildpack-elixir/pull/146
* With https://github.com/HashNuke/heroku-buildpack-elixir/pull/151
* Due to issue filed at https://github.com/HashNuke/heroku-buildpack-elixir/issues/150

We can take our time to resolve the issue and then move ahead with the PR.

**Pull request merged**
