### PR TITLE
Add precompile hook

### PR DESCRIPTION
**Pull request by novaugust**
A very lazy pull request that more-or-less copy and pastes the changes from #39.

I needed this because one of the templates for my phoenix app is generated by another command that must be run before the application compiles (otherwise, I compile with a missing template..). Running off my fork, but thought it might be useful to others as well.

### CODE REVIEW

**Comment by ericmj** [comment]
LGTM. Out of curiosity, what do you have that generates the templates?

Have you considered making it a proper mix compile task? Might be cleaner.

**Comment by novaugust** [comment]
> Have you considered making it a proper mix compile task? Might be cleaner.

I haven't. You mean by aliasing the compile command in mix.exs? And the task we're running is building an ember application, and subbing its generated index.html into an index.html.eex in our templates.

---------------------

I'm actually not convinced you folks should merge this after all =)

I ended up building my own buildpack ([novaugust/heroku-buildpack-phoenix](/novaugust/heroku-buildpack-phoenix)) that combines all the work done by this buildpack along with the node installs provided by the [phoenix static buildpack](/gjaldon/heroku-buildpack-phoenix-static), as well as the static buildpack's method of complete customization of what `compile` does. 

That way you just override a file with all the commands you need run to do your compilation, rather than having to tack on pre / post compiles and add bloat, which I think this PR does to buildpack-elixir.

So, since the work's already done, I won't close this PR, but if you decide against it I wouldn't be hurt in the slightest =)

(My buildpack hasn't updated the readme - I think it's verbatim this repo's readme, as i started from a fork. Someday..)

**Comment by HashNuke** [comment]
@novaugust incase you are working on a fork, I would request that you retain git commit history to give credit to contributors here.

**Comment by novaugust** [comment]
That repo is the merger of two totally separate repos; my git-fu (and time constraints) weren't up to the task of maintaining both histories. You did motivate me to finally update the readme to something original (if not exactly useful yet) at least ;)

**Comment by HashNuke** [comment]
@novaugust I'm glad you got it working.

If you are keeping it opensource, I'm very particular about the git history, because credit is a positive side-effect of contributing to opensource. If a fork exists then I would request that the fork retain the entire git history of this repository. There are multiple articles available to perform such operations. Please look it up.

P.S: The license file too.

**Comment by ericmj** [comment]
LGTM, I think we should merge this if it's ready.

**Comment by HashNuke** [comment]
@novaugust Merged ~! Thank you :)

**Pull request merged**
