### PR TITLE
Allow the elixir app to reside in a subdirectory.

### PR DESCRIPTION
**Pull request by jwietelmann**
I'll be the first to admit not fully testing this outside of my own use case, but I wanted to throw this out there early and get feedback. Nothing methodical about it. Just hacked at it til it worked.

### CODE REVIEW

**Comment by ericmj** [comment]
What's the use-case for this?

**Comment by jwietelmann** [comment]
@ericmj I have a starter apps boilerplate repo. It involves multiple languages, so to keep things organized I have the following directory setup:

```
elixir/
node/
ruby/
```

Directory structure conventions of Phoenix or Rails apps makes keeping them at the top-level directory a non-starter in this case. That's why I start off with Elixir in a subdirectory in the first place.

That `node` directory contains all my React HTML-rendering code. It's a dumb service that you send JSON to (example http://revelry-hybrid.herokuapp.com/jsonui), and it sends back an HTML string (example http://revelry-hybrid.herokuapp.com/). Because it's a dumb service it's portable to whichever language I want to write the meat of my app in, so I'll either keep `ruby` or `elixir` and delete the other.

So I've got:

```
elixir/
node/
```

I could deploy those to separate Heroku apps and have them just communicate over the web, which is great for independently scaling the two concerns. In that case I could just use `git subtree`, and the buildpack wouldn't need any changes. But then I have to manage keeping two Heroku apps version-synced. More often than not I just start Elixir on `PORT`, Node on a different available port on the same dyno, and have them communicate over the internal network on the dyno until such time as I might need to separate them.

So `git subtree` isn't an adequate solution because I need one app to have both the `elixir` and `node` directories.

I realize my setup is a little on the esoteric side, but I also doubt I'm the only person who will ever want to ship a polyglot app where Elixir isn't at the root.

**Comment by ericmj** [comment]
Do the official heroku buildpacks for node and ruby support the same `app_subdirectory` option? If so, I think this is the way to go. If not, are you planning to contribute the same path to the other buildpacks or do you only need it for elixir?

**Comment by jwietelmann** [comment]
They do not, and I do not.

Those buildpacks are easily accommodated by moving just `Gemfile` and `package.json` into the root, which is a simple, mostly unobtrusive change. However, it appears from my other workaround attempts that moving `mix.exs` into the root and modifying the paths it defines appears to create a host of problems for a straight-from-the-generator Phoenix app, even before ever shipping it to Heroku.

**Comment by jwietelmann** [comment]
Might have found an alternative that isn't awesome but also seems to be the way this world is going anyway: Make the Phoenix app belong to an umbrella whose mix.exs is at the root. Let the umbrella configure paths and such. Appears to work.

**Comment by CrowdHailer** [comment]
I have an elixir project that is in a subdirectory that I want to deploy on heroku. 
The elixir app exists in a directory called `project`. The reason for this is I still have some legacy ruby code that is responsible for migrations that this code resides in the root directory.

**Comment by TranDinhKhang** [comment]
Hey, would you fix conflicts to merge?
I'm having same problems with you @jwietelmann

**Comment by tkhduracell** [comment]
@jwietelmann ping..

**Comment by jwietelmann** [comment]
Stop rudely pinging me. I'm not a maintainer of this project, and you could have just been using my out-of-date fork this entire time, or you could just do the work if you care so much.

**Comment by tkhduracell** [comment]
Thanks, then I know :) 
(Are pings rude?)

**Pull request closed without merging**
