### PR TITLE
Use Hex's precompiled erlang

### LINKED ISSUE #10: Failing to install Erlang 17.1
Not sure this is a bug or if I'm misaddressing the Erlang version, but using this `elixir_buildpack.config` the installation of Erlang fails. 

```
erlang_version=17.1

elixir_version=0.14.3

always_build_deps=false
```

I got this error message:

```
% g push heroku master
Fetching repository, done.
Counting objects: 19, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 1.21 KiB | 0 bytes/s, done.
Total 13 (delta 8), reused 0 (delta 0)

-----> Fetching custom git buildpack... done
-----> elixir app detected
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Erlang 17.1
       * Elixir 0.14.3
       Downloading Erlang package
-----> Fetching Erlang 17.1
-----> Installing Erlang 17.1

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Exiting with failure status due to previous errors
/tmp/buildpack_809d2e12-f3eb-495e-b37a-dcaea4e66f9d/lib/erlang_funcs.sh: line 61: /app/tmp/cache/erlang/Install: No such file or directory
-----> [skip] Already downloaded Elixir 0.14.3
-----> Unpacking Elixir 0.14.3
-----> Installing Elixir 0.14.3
-----> Installing Hex
exec: 93: erl: not found
-----> Installing rebar
exec: 93: erl: not found
-----> Fetching app dependencies with mix
exec: 93: erl: not found

 !     Push rejected, failed to compile elixir app
```

### PR DESCRIPTION
**Pull request by ericmj**
Closes #10.

### CODE REVIEW

**Comment by duksis** [comment]
@ericmj could it be possible to get R16B on S3 as well?
https://gist.github.com/duksis/3a722a0a2dead78afd01

**Comment by ericmj** [comment]
@duksis Sorry, we don't support elixir <1.0.0. Even if we push R16B it's unlikely the buildpack will work with an elixir that old.

**Comment by HashNuke** [comment]
@dukis you could point Heroku to an older commit of the buildpack that supports R16.

https://github.com/HashNuke/heroku-buildpack-elixir.git#yourCommitShaHere

I think R16 was supported in April-2014 or so. So use a commit from back then. Just note that the docs and the settings for the buildpack are different now. So you'll have to follow the older docs. I don't think there was Erlang precompilation back then.

**Comment by duksis** [comment]
@ericmj, @HashNuke thanks for the quick response - I try to figure something out to get my legacy stuff running with this build pack :)

**Pull request merged**
