### PR TITLE
erl in ci:debug

### PR DESCRIPTION
**Pull request by myobie**
These changes make the buildpack work during Heroku CI as part of a pipeline and with the `ci:debug` cli command.

### CODE REVIEW

**Comment by venkatd** [comment]
I can confirm this resolved my issue of erlang not being available and the tests failing as part of a Heroku pipeline.

**Comment by HashNuke** [comment]
@anulman since you tinkered with the buildpack recently: Does this PR still help?

**Comment by anulman** [comment]
@HashNuke I was not using Heroku's `ci` features. I would assume so

**Comment by myobie** [comment]
I just tested using `https://github.com/HashNuke/heroku-buildpack-elixir.git` master and I was able to successfully run `$ heroku ci:run --pipeline test-for-elixir` and `$ heroku ci:debug --pipeline test-for-elixir` (where I ran `$ mix test`). 

I believe this might have been fixed in master sometime after this PR was created. I feel comfortable closing this.

**Comment by DavidMikeSimon** [comment]
@myobie I'm still unable to get ci:debug working on the upstream branch, but it works great on your fork. Please consider re-opening your PR!

**Comment by myobie** [comment]
@DavidMikeSimon do you have an example repo?

**Comment by jc00ke** [comment]
I'm seeing this with an app right now. Would love to see this PR reopened and merged. :heart:

**Comment by jesseshieh** [comment]
@jc00ke do you have an example repo I can use to test? Does the fix here resolve your issue?
You can specify which branch to use when specifying which buildpack to use I believe.

**Comment by jesseshieh** [comment]
@jc00ke actually, it looks like it's just https://github.com/myobie/heroku-buildpack-elixir without a branch. Can you see if your issue is resolved with the above buildpack? 

It also looks like there is a conflict that needs to be resolved. If the fix does indeed work, @myobie do you mind resolving the conflict?

**Comment by myobie** [comment]
Just FYI, I've actually been using a new [buildpack I created to use elixir releases](https://github.com/shareup/heroku-buildpack-elixir-release) and haven't been maintaining my fork. I did resolve the conflict but I didn't fully test the result.

**Comment by jc00ke** [comment]
@jesseshieh will give it a try on Monday!

**Comment by jc00ke** [comment]
@jesseshieh worked great!

**Comment by jesseshieh** [comment]
Just tested on a basic, non-heroku-ci deploy and all seemed to work fine. I'm slightly worried about merging this because I'm not sure I understand all the different edge cases if any, but these changes seem to solve a demonstrated problem and I haven't found any regressions. I also can't think of any reason why this would break any existing apps, but that is based on my less than perfect knowledge of how this buildpack works as a new maintainer. There aren't great tests to verify that this doesn't break anything, but I'm okay with merging this in the interest of moving forward rather than freezing the buildpack from any new features or complicated bug fixes.

**Comment by jesseshieh** [comment]
Sorry guys, looks like this caused deploy failures for a number of people in https://github.com/HashNuke/heroku-buildpack-elixir/issues/167. I haven't figured out exactly what is happening, but I had to revert this PR.

**Pull request merged**
