### PR TITLE
Update defaults to Elixir 1.8.1 and Erlang 21.3.3

### PR DESCRIPTION
**Pull request by HashNuke**
This should resolve https://github.com/phoenixframework/phoenix/issues/3360

### CODE REVIEW

**Comment by jesseshieh** [comment]
Looks like https://github.com/phoenixframework/phoenix/issues/3360 was resolved by updating the documentation, but I think it might be a good idea to define a process by which we can upgrade the default elixir and erlang versions without breaking existing apps. Any thoughts on the best way to do that?

One option is to simply give people adequate notice that it is happening by printing a large warning message. 

Another option is to "save" the elixir and erlang version somewhere (build cache?) so that subsequent changes to the defaults don't affect existing apps.

My guess is we'll need to do some form of both the above, but I worry that this will cause more confusion that it's worth. Perhaps it's better to simply do nothing at all. What do you think?

**Comment by wojtekmach** [comment]
Just wanted to mention that the current default version of Elixir 1.5 no longer receives security patches: https://hexdocs.pm/elixir/compatibility-and-deprecations.html#content. For this reason I'd seriously consider bumping to at least 1.6.

But yeah, not sure what's the best way forward taking into account backwards compatibility for existing apps.

Perhaps we could add a simple heuristic that looks for `elixir: "~> X.Y"` in `mix.exs` and if it finds it it uses it (again, the heuristic would be as simple as possible, we definitely don't want to re-implement semver in bash) and if not, it uses the default. This means that recently created projects (with more recent elixir version requirement) would get a more recent version by default and there's no downside to that because they couldn't run on older versions anyway.

The only other thing is umbrella projects usually don't have an elixir version requirement in the mix.exs so we wouldn't infer that, but that's probably ok as these projects tend to have more tailored configuration anyway.

What do you think?

**Comment by jesseshieh** [comment]
@wojtekmach thanks for the heads up. I like the heuristic you described.

**Comment by wojtekmach** [comment]
Another solution we briefly discussed with José was to deprecate these default values (warn it would be removed at some point) and force people to set them explicitly which folks definitely should do anyway. If the heuristic turns out not to be a good solution I think thatd be the way to go, or it should be the way to go regardless.

**Comment by jesseshieh** [comment]
I like that also. Do you have a sense of how long the warning period should be? 

One reason I like removing the default entirely is that then no apps would silently get upgraded without the developer's knowledge, which may cause mysterious issues that the developer may have a hard time tracking down. Instead, the app would simply fail to deploy and force them to explicitly set a version.

**Comment by wojtekmach** [comment]
I honestly don’t know, I’d arbitrarily say at least 6 months. Maybe soon after Elixir v1.12 is out next year would be a good time since they’ll drop support for another oldest version.

I vaguely remember you can version your buildpacks so that’s a separate but additional thing we could do. perhaps new users should use #v1 (or whenever you want to start at) and that’d already force explicit settings.

**Comment by jesseshieh** [comment]
@wojtekmach Here's the warning in case you want to take a look https://github.com/HashNuke/heroku-buildpack-elixir/pull/185

**Comment by jesseshieh** [comment]
Removing defaults here
https://github.com/HashNuke/heroku-buildpack-elixir/pull/209

**Pull request closed without merging**
